services:
  db:
    image: mariadb:latest
    container_name: klodweb-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: klodwebsite
      MYSQL_USER: klodadmin
      MYSQL_PASSWORD: Pw3Lqb6fuLspT7IrYp
    volumes:
      - db_data:/var/lib/mysql
      - ./setup/website.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - klodweb-net

  php:
    image: bitnami/php-fpm:latest
    container_name: klodweb-php
    volumes: 
    - ./www:/app 
    depends_on:
      - db
    networks:
      - klodweb-net

  apache:
    image: bitnami/apache:latest
    container_name: klodweb-apache
    ports:
      - "1443:8443"
    depends_on:
      - php
    networks:
      - klodweb-net
    volumes:
      - ./www:/app 
      - ./setup/apache.conf:/vhosts/klodweb.conf:ro

volumes:
  db_data:

networks:
  klodweb-net:
